# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:

env_files:
  github_token: /root/projects/keys/main

builds:
  -
    binary: wzd
    id: wzd
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - openbsd
      - netbsd
      - solaris
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64
      - mips64
    goarm:
      - 7

release:
  draft: false

archives:
  -
    id: "wzd"
    builds: ['wzd']
    format: tar.gz
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    files:
      - LICENSE

nfpms:
  -
    id: "wzd"
    builds: ['wzd']
    formats:
      - deb
      - rpm
    vendor: "Eltaline"
    homepage: "https://wzd.dev/"
    maintainer: "Andrey Kuvshinov <dev@wzd.dev>"
    description: "Sharded NoSQL Compact Storage Server. Distributing any number of small and large files/values"
    license: "BSD-3 Clause"
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"

    bindir: /usr/sbin

    dependencies:
      - systemd
      - logrotate

    empty_folders:
      - /etc/wzd
      - /var/log/wzd
      - /var/lib/wzd
      - /usr/share/wzd

    files:
      "conf/systemd/wzd.service": "/lib/systemd/system/wzd.service"
      "conf/logrotate.d/wzd": "/etc/logrotate.d/wzd"
      "LICENSE": "/usr/share/wzd/LICENSE"

    config_files:
      "conf/wzd/wzd.conf": "/etc/wzd/wzd.conf"
      "conf/wzd/get-localhost.conf": "/etc/wzd/get-localhost.conf"
      "conf/wzd/put-localhost.conf": "/etc/wzd/put-localhost.conf"
      "conf/wzd/del-localhost.conf": "/etc/wzd/del-localhost.conf"

    scripts:
      postinstall: "scripts/postinstall.sh"

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''

    binaries:
    - wzd

    builds:
    - wzd

    image_templates:
    - "eltaline/wzd:latest"
    - "eltaline/wzd:{{.Version}}"

    skip_push: false

    dockerfile: Dockerfile

    build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.name={{.ProjectName}}"

    # If your Dockerfile copies files other than the binary itself,
    # you should list them here as well.
    # Note that goreleaser will create the same structure inside the temporary
    # folder, so if you add `foo/bar.json` here, on your Dockerfile you can
    # `COPY foo/bar.json /whatever.json`.
    # Also note that the paths here are relative to the folder in which
    # goreleaser is being run.
    # This field does not support wildcards, you can add an entire folder here
    # and use wildcards when you `COPY`/`ADD` in your Dockerfile.
    extra_files:
    - conf/wzd/docker/wzd-docker.conf
    - conf/wzd/docker/get-localhost.conf
    - conf/wzd/docker/put-localhost.conf
    - conf/wzd/docker/del-localhost.conf
    - scripts/docker/start.sh
    - LICENSE

scoop:

  commit_author:
    name: "Andrey Kuvshinov"
    email: dev@wzd.dev
  homepage: "https://wzd.dev/"
  license: BSD-3 Clause

brews:
 -
   commit_author:
     name: "Andrey Kuvshinov"
     email: dev@wzd.dev
   homepage: "https://wzd.dev/"
   goarm: 7

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Version}}-master"
changelog:
  sort: asc
  filters:
    exclude:
    - README
    - OPTIONS
    - Readme
    - Options
    - Image
    - Script
    - Docker
    - Typo
    - "via upload"
    - goreleaser
